//+------------------------------------------------------------------+
//| NewsFilter.mqh - USD high-impact news blackout                   |
//| Reads Common\Files\<file>: one server-time timestamp per line,   |
//| "YYYY.MM.DD HH:MI" (generated by tools/export_news.py with the   |
//| calendar(UTC+3 fixed) -> server(UTC+2/+3, US DST) conversion).   |
//+------------------------------------------------------------------+
#property strict

class CNewsFilter
  {
private:
   datetime          m_t[];
   int               m_n;
   int               m_before;     // minutes, no entries before news
   int               m_after;      // minutes, no entries after news
   int               m_flat;       // minutes, flatten before news

   int               NextIdx(datetime t)
     {
      int lo = 0, hi = m_n;
      while(lo < hi)
        {
         int mid = (lo + hi) / 2;
         if(m_t[mid] < t) lo = mid + 1; else hi = mid;
        }
      return lo;
     }

public:
   bool              Load(string file, int before, int after, int flat)
     {
      m_before = before; m_after = after; m_flat = flat; m_n = 0;
      int h = FileOpen(file, FILE_READ | FILE_TXT | FILE_ANSI | FILE_COMMON);
      if(h == INVALID_HANDLE)
        {
         PrintFormat("[News] cannot open %s (err %d)", file, GetLastError());
         return false;
        }
      ArrayResize(m_t, 0, 8192);
      while(!FileIsEnding(h))
        {
         string s = FileReadString(h);
         if(StringLen(s) < 10)
            continue;
         datetime t = StringToTime(s);
         if(t <= 0)
            continue;
         ArrayResize(m_t, m_n + 1, 8192);
         m_t[m_n++] = t;
        }
      FileClose(h);
      ArraySort(m_t);
      PrintFormat("[News] %d events loaded, last=%s", m_n, m_n > 0 ? TimeToString(m_t[m_n - 1]) : "-");
      return m_n > 0;
     }

   datetime          LastEvent() { return m_n > 0 ? m_t[m_n - 1] : 0; }

   //--- no entry if a news event is within (t - after, t + before)
   bool              BlockEntry(datetime t)
     {
      int i = NextIdx(t);
      if(i < m_n && m_t[i] - t < m_before * 60)
         return true;
      if(i > 0 && t - m_t[i - 1] < m_after * 60)
         return true;
      return false;
     }

   //--- close open positions when the next news is less than m_flat(+1) minutes away
   bool              MustFlatten(datetime t)
     {
      int i = NextIdx(t);
      return (i < m_n && m_t[i] - t < (m_flat + 1) * 60);
     }
  };
